FROM node:8.16.0

WORKDIR /usr/app

COPY package*.json .

RUN npm install    

COPY . .

ENV NODE_ENV=production
ENV DB_HOST=ds059712.mlab.com
ENV DB_PORT=59712
ENV DB_NAME=catalyst
ENV DB_USER=developer
ENV DB_PASS=developer1
ENV YARN_PRODUCTION=false
ENV PAYMAYA_SEC_KEY=sk-VGDKY3P90NYZZ0kSWqBFaD1NTIXQCxtdS7SbQXvcA4g
ENV PAYMAYA_PUB_KEY=pk-yaj6GVzYkce52R193RIWpuRR5tTZKqzBWsUeCkP9EAf

EXPOSE 3000

CMD [ "npm", "start" ]
